name: "✨ Feature Request"
description: Sugira uma nova funcionalidade para o J.A.R.V.I.S.
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Qual problema isso resolve?
      description: Descreva a limitação ou necessidade atual.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Solução proposta
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
